### ISSUE TITLE
Improve Subject Claim Configuration for TraTs

### ISSUE THREAD

**Issue by kchiranjewee63** [tokenetes/tokenetes#65]
## Current Behavior

The current configuration for subject claims in TraT is not intuitive and lacks clarity. The configuration is done through TokenetesConfig, but the connection between this configuration and how it populates the `sub` field in TraT is not clear.

Current configuration structure example:

```yaml
subjectTokens:
  OIDC:
    clientId: alpha-stocks-client
    providerURL: http://dex:5556/dex
    subjectField: email
  selfSigned:
    validation: false
    jwksEndpoint: "http://alphastocks.com/oidcprovider/.well-known/jwks.json"
```

## Issues with Current Approach

1. The configuration doesn't clearly indicate its relation to the `sub` field in TraT.
2. For self-signed tokens, it's unclear how the `sub` field is populated.
3. OIDC token configuration currently only supports email.

## Desired Behavior

A more intuitive and flexible way to configure how the `sub` field in TraT is populated, with clear documentation on how different token types are handled.

## Potential Solution (for discussion)

1. Add a `sub` field in the TraT resource, similar to `issuer` and `audience`.
2. Use variable notation (e.g., `${subjectToken.subject.email}`) to specify how the `sub` field should be populated.
3. Provide clear documentation on how different token types (OIDC, self-signed) are processed.
